development:
  perform_authentication: false
  TWILIO_SID: "AC42cf4f0c39d95f6000d765fe11688f0c"
  TWILIO_TOKEN: "db0f7923141aed6f289d034472324de0"
  TWILIO_PHONE_NUMBER: "12063506218"
  email: <%= ENV['EMAIL'] %>
  pass: <%= ENV['EMAIL_PASS'] %>
  host_url: "localhost:3000"


test:
  perform_authentication: false

production:
  perform_authentication: true
  username: admin
  password: secret
  email: <%= ENV['EMAIL'] %>
  pass:  <%= ENV['EMAIL_PASS'] %>
  host_url: "https://nameless-citadel-48731.herokuapp.com"
  TWILIO_SID: "AC4fde6f50b9fbb580923236b691bfc8e2"
  TWILIO_TOKEN: "ae29da2b47bc7697f2176a72d9123516"
  TWILIO_PHONE_NUMBER: "4155238886"
